# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

workspace 'Zwallet'

pod 'OTPFieldView'

def common_dependency
  pod 'Kingfisher'
end

target 'App' do
  pod 'Moya'
  pod 'netfox', :configurations => ['Debug']
  common_dependency
end

target 'Core' do
  project '../Module/Core/Core'

  pod 'Moya'
  common_dependency
end

target 'History' do
  project '../Module/History/History'

  common_dependency
end

target 'Home' do
  project '../Module/Home/Home'

  common_dependency
end

target 'Login' do
  project '../Module/Login/Login'
end

target 'SignUp' do
  project '../Module/SignUp/SignUp'
end

target 'CreatePin' do
project '../Module/CreatePin/CreatePin'
end

target 'Receiver' do
project '../Module/Receiver/Receiver'
end

target 'InputAmount' do 
  project '../Module/InputAmount/InputAmount'
end

target 'ConfirmationTransaction' do
  project '../Module/ConfirmationTransaction/ConfirmationTransaction'
  common_dependency
end

target 'PinConfirmation' do
  project '../Module/PinConfirmation/PinConfirmation'
end

target 'TransactionStatus' do
  project '../Module/TransactionStatus/TransactionStatus'
  common_dependency
end
